version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/qr_event
      - NODE_ENV=production
      - CLIENT_ORIGIN=http://localhost:5173
    ports:
      - "5699:5699"
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_API_BASE=http://localhost:5699/api
        - VITE_PUBLIC_BASE_URL=http://localhost:5173
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data:
